names:
- nodules and cysts
- papules
- pustules
- whitehead and blackhead
nc: 4
test: /Users/krangwala/Desktop/Research/Yang lab/yanglab-acne/data/acne04/test/images
train: /Users/krangwala/Desktop/Research/Yang lab/yanglab-acne/data/acne04/train/images
val: /Users/krangwala/Desktop/Research/Yang lab/yanglab-acne/data/acne04/valid/images
